name: Upload Missing Files

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload macOS Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-macOS
          path: |
            build/bin/data
            build/bin/aseprite
